services:
  - type: web
    name: backbread
    rootDir: .
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_BASE_URL
        value: https://backbread.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://son-bread.vercel.app
      - key: MAX_FILE_SIZE
        value: "5242880"
      - key: UPLOAD_PATH
        value: /opt/render/project/src/uploads
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
    disk:
      name: uploads-disk
      mountPath: /opt/render/project/src/uploads
      sizeGB: 5
